### PR TITLE
Use xnoremap for visual mode mappings

### PR DESCRIPTION
**Pull request by suy**
Hi!

As you know, AutoClose uses vnoremap for the actions that wrap the visual selection. However, vnoremap maps _both_ visual and select modes. Select mode is not very well known, but is very useful for snippets plugins. The Vim documentation advises against mapping printable characters in select mode (see :h Select-mode-mapping or :h mapmode-x) because it might confuse the user. In my case is causing me a conflict with the plugin UltiSnips.

This simple change fixes this.
Thank you!

### CODE REVIEW

**Comment by suy** [comment]
Hi.

I've updated the commit (it was 32a5a29) to apply to current master (now is 85e22d4). Just in case I didn't explain myself properly, the change is use xnoremap to still map the keys in visual mode, but not map them in select mode (vnoremap maps both modes).

Thank you.

**Comment by artm** [comment]
good idea

**Comment by artm** [comment]
I pulled it locally and tested, it works as expected and I agree with the rationale. This request has my vote.

**Comment by suy** [comment]
Thank you!

**Comment by Townk** [comment]
No no, thank YOU :)
Patches and improvements are always welcome!

**Pull request merged**
